# SonarCloud Project Configuration

# Unique project identifier
sonar.projectKey=gjarunselvan_Github_Action_Example

# Your SonarCloud organization ID
sonar.organization=gjarunselvan

# Source directories to scan
sonar.sources=sample-app

# Exclude test files from being analyzed as application code
sonar.exclusions=**/*.test.js

# Programming language
sonar.language=js

# Encoding of the source code
sonar.sourceEncoding=UTF-8
