name: 07 - Caller Workflow

on:
  push:
    branches: [ "main" ]

jobs:
  call-reusable-workflow:
    uses: ./.github/workflows/07-reusable-workflow.yml
    with:
      config-path: './config/production.json'
    secrets:
      token: ${{ secrets.GITHUB_TOKEN }}
