name: 07 - Reusable Template

# 'workflow_call' explicitly designates this file as a callable blueprint (DRY principle)
on:
  workflow_dispatch:
  workflow_call:
    # Define parameters that the Caller workflow MUST provide
    inputs:
      target_env:
        required: true
        type: string
    # Define secure secrets that the Caller workflow MUST provide
    secrets:
      token:
        required: true

jobs:
  deploy-template:
    runs-on: ubuntu-latest
    steps:
      - name: Deploying using template
        run: |
          echo "Deploying to requested environment: ${{ inputs.target_env }}"
          echo "Using provided token: ***"
