name: 08 - Contexts and Expressions

on: [push, pull_request]

jobs:
  print-context:
    runs-on: ubuntu-latest
    steps:
      - name: Dump GitHub context
        env:
          GITHUB_CONTEXT: ${{ toJSON(github) }}
        run: echo "$GITHUB_CONTEXT"

      - name: Run only on main branch
        if: github.ref == 'refs/heads/main'
        run: echo "This runs only when pushed to the main branch."
