name: 10 - Environment Variables and Secrets

on: [push]

env:
  GLOBAL_ENV: "Available to all jobs and steps"

jobs:
  demo-env-secrets:
    runs-on: ubuntu-latest
    env:
      JOB_ENV: "Available only to this job"
    steps:
      - name: Print Variables
        env:
          STEP_ENV: "Available only to this step"
        run: |
          echo "Global Env: $GLOBAL_ENV"
          echo "Job Env: $JOB_ENV"
          echo "Step Env: $STEP_ENV"
      
      - name: Use Secret
        run: |
          echo "You cannot print secrets, but you can pass them to commands."
          # example: curl -H "Authorization: token ${{ secrets.API_TOKEN }}" https://api.example.com
