name: 10 - Environments and Secrets

on:
  workflow_dispatch:

# We can define Environment Variables that are available globally across all jobs
env:
  GLOBAL_APP_NAME: "My Awesome App"

jobs:
  deploy-to-prod:
    runs-on: ubuntu-latest
    # Tying this job to an 'environment' enables GitHub protection rules (e.g., Manual Approvals)
    environment: production
    
    steps:
      - name: Print Variables
        run: |
          echo "App Name: $GLOBAL_APP_NAME"
          
      # We securely inject the hidden token using ${{ secrets.XXX }}
      # GitHub automatically masks this value with '***' in all public logs
      - name: Secure Login
        run: |
          echo "Logging in securely..."
          echo "Token is: ${{ secrets.SUPER_SECRET_TOKEN }}"
