name: 11 - Dependency Caching

on:
  push:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      
      # The actions/cache tool saves folders between workflow runs to speed up builds
      - name: Cache Node Modules
        uses: actions/cache@v4
        with:
          # We specify the exact folder path we want to zip and save
          path: ~/.npm
          # The cache 'key' uses a hash of package.json. If package.json changes, the hash changes, invalidating the cache!
          key: npm-${{ hashFiles('**/package.json') }}
          # Fallback key if exact match isn't found
          restore-keys: |
            npm-
            
      # Because of the cache above, this step might take 2 seconds instead of 2 minutes!
      - name: Install dependencies
        run: npm install
